// GENERATED by tools/build_balance.py from data/balance/*.csv. Do not edit by hand.
// Loads before the other bo1sz_* files (alphabetical); they wait for level.bo1sz_bal.

init()
{
	level.bo1sz_bal = [];
	// style.csv
	level.bo1sz_bal[ "style.gauge_max" ] = 100;
	level.bo1sz_bal[ "style.idle_grace_ms" ] = 2000;
	level.bo1sz_bal[ "style.drop_refill" ] = 0.6;
	level.bo1sz_bal[ "style.popup_seconds" ] = 1.6;
	level.bo1sz_bal[ "style.sound_rank_up" ] = "zmb_cha_ching";
	level.bo1sz_bal[ "style.sound_rank_down" ] = "evt_perk_deny";
	level.bo1sz_bal[ "style.fake_min" ] = 10;
	level.bo1sz_bal[ "style.fake_max" ] = 40;
	level.bo1sz_bal[ "style.fake_interval_ticks" ] = 6;
	// style_ranks.csv
	level.bo1sz_style_ranks_letter = [];
	level.bo1sz_style_ranks_word = [];
	level.bo1sz_style_ranks_gain_mult = [];
	level.bo1sz_style_ranks_decay_per_sec = [];
	level.bo1sz_style_ranks_r = [];
	level.bo1sz_style_ranks_g = [];
	level.bo1sz_style_ranks_b = [];
	level.bo1sz_style_ranks_letter[ 0 ] = "D";
	level.bo1sz_style_ranks_word[ 0 ] = "Dawdling";
	level.bo1sz_style_ranks_gain_mult[ 0 ] = 1.0;
	level.bo1sz_style_ranks_decay_per_sec[ 0 ] = 3;
	level.bo1sz_style_ranks_r[ 0 ] = 0.70;
	level.bo1sz_style_ranks_g[ 0 ] = 0.70;
	level.bo1sz_style_ranks_b[ 0 ] = 0.70;
	level.bo1sz_style_ranks_letter[ 1 ] = "C";
	level.bo1sz_style_ranks_word[ 1 ] = "Cold-Blooded";
	level.bo1sz_style_ranks_gain_mult[ 1 ] = 0.9;
	level.bo1sz_style_ranks_decay_per_sec[ 1 ] = 6;
	level.bo1sz_style_ranks_r[ 1 ] = 0.55;
	level.bo1sz_style_ranks_g[ 1 ] = 0.80;
	level.bo1sz_style_ranks_b[ 1 ] = 1.00;
	level.bo1sz_style_ranks_letter[ 2 ] = "B";
	level.bo1sz_style_ranks_word[ 2 ] = "Butcher";
	level.bo1sz_style_ranks_gain_mult[ 2 ] = 0.8;
	level.bo1sz_style_ranks_decay_per_sec[ 2 ] = 8;
	level.bo1sz_style_ranks_r[ 2 ] = 0.45;
	level.bo1sz_style_ranks_g[ 2 ] = 1.00;
	level.bo1sz_style_ranks_b[ 2 ] = 0.55;
	level.bo1sz_style_ranks_letter[ 3 ] = "A";
	level.bo1sz_style_ranks_word[ 3 ] = "Annihilator";
	level.bo1sz_style_ranks_gain_mult[ 3 ] = 0.7;
	level.bo1sz_style_ranks_decay_per_sec[ 3 ] = 11;
	level.bo1sz_style_ranks_r[ 3 ] = 1.00;
	level.bo1sz_style_ranks_g[ 3 ] = 0.90;
	level.bo1sz_style_ranks_b[ 3 ] = 0.30;
	level.bo1sz_style_ranks_letter[ 4 ] = "S";
	level.bo1sz_style_ranks_word[ 4 ] = "Slaughterhouse";
	level.bo1sz_style_ranks_gain_mult[ 4 ] = 0.6;
	level.bo1sz_style_ranks_decay_per_sec[ 4 ] = 14;
	level.bo1sz_style_ranks_r[ 4 ] = 1.00;
	level.bo1sz_style_ranks_g[ 4 ] = 0.60;
	level.bo1sz_style_ranks_b[ 4 ] = 0.15;
	level.bo1sz_style_ranks_letter[ 5 ] = "SS";
	level.bo1sz_style_ranks_word[ 5 ] = "Spine-Shattering";
	level.bo1sz_style_ranks_gain_mult[ 5 ] = 0.5;
	level.bo1sz_style_ranks_decay_per_sec[ 5 ] = 18;
	level.bo1sz_style_ranks_r[ 5 ] = 1.00;
	level.bo1sz_style_ranks_g[ 5 ] = 0.30;
	level.bo1sz_style_ranks_b[ 5 ] = 0.20;
	level.bo1sz_style_ranks_letter[ 6 ] = "SSS";
	level.bo1sz_style_ranks_word[ 6 ] = "Supreme Slayer";
	level.bo1sz_style_ranks_gain_mult[ 6 ] = 0.4;
	level.bo1sz_style_ranks_decay_per_sec[ 6 ] = 22;
	level.bo1sz_style_ranks_r[ 6 ] = 0.85;
	level.bo1sz_style_ranks_g[ 6 ] = 0.25;
	level.bo1sz_style_ranks_b[ 6 ] = 1.00;
	level.bo1sz_style_ranks_count = 7;
}
