#!/usr/bin/env python3
"""Generate src/scripts/mod/bo1sz_balance.gsc from data/balance/*.csv.

Two CSV shapes:
  key,value,notes        -> level.bo1sz_bal["<file>.<key>"] = <value>;
  any other header       -> one array per column: level.bo1sz_<file>_<column>[i] = <cell>;
                            plus level.bo1sz_<file>_count = <rows>;
Numbers are emitted as numbers, everything else as strings.

Usage:
  python tools/build_balance.py          # write the generated file
  python tools/build_balance.py --check  # exit 1 if the generated file is stale (CI)
"""
import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "balance"
OUT = ROOT / "src" / "scripts" / "mod" / "bo1sz_balance.gsc"
NUM = re.compile(r"^-?\d+(\.\d+)?$")
IDENT = re.compile(r"^[a-z][a-z0-9_]*$")


def lit(v: str) -> str:
    v = v.strip()
    if NUM.match(v):
        return v
    if '"' in v or "\\" in v:
        raise ValueError(f"unsupported character in value: {v!r}")
    return f'"{v}"'


def render() -> str:
    lines = [
        "// GENERATED by tools/build_balance.py from data/balance/*.csv. Do not edit by hand.",
        "// Loads before the other bo1sz_* files (alphabetical); they wait for level.bo1sz_bal.",
        "",
        "init()",
        "{",
        "\tlevel.bo1sz_bal = [];",
    ]
    for path in sorted(DATA.glob("*.csv")):
        name = path.stem
        if not IDENT.match(name):
            raise ValueError(f"bad csv name {path.name}")
        with path.open(newline="", encoding="utf-8") as fh:
            rows = list(csv.DictReader(fh))
            header = [h.strip() for h in (rows[0].keys() if rows else [])]
        lines.append(f"\t// {path.name}")
        if header[:2] == ["key", "value"]:
            for r in rows:
                key = r["key"].strip()
                if not IDENT.match(key):
                    raise ValueError(f"{path.name}: bad key {key!r}")
                lines.append(f'\tlevel.bo1sz_bal[ "{name}.{key}" ] = {lit(r["value"])};')
        else:
            for col in header:
                if not IDENT.match(col):
                    raise ValueError(f"{path.name}: bad column {col!r}")
                lines.append(f"\tlevel.bo1sz_{name}_{col} = [];")
            for i, r in enumerate(rows):
                for col in header:
                    lines.append(f"\tlevel.bo1sz_{name}_{col}[ {i} ] = {lit(r[col])};")
            lines.append(f"\tlevel.bo1sz_{name}_count = {len(rows)};")
    lines += ["}", ""]
    return "\n".join(lines)


def main(argv):
    text = render()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current.replace("\r\n", "\n") != text:
            print("bo1sz_balance.gsc is stale: run python tools/build_balance.py")
            return 1
        print("bo1sz_balance.gsc is up to date")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
